config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard', as: :dashboard
  get 'profile', to: 'pages#profile', as: :profile
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cars
  resources :driver_requirement, except: [:destroy]
  get "rides/:id/status", to: "rides#status", as: :ride_status
  resources :rides, except: :destroy do
    get 'payments/add_card', to: 'payments#add_card', as: :add_card
    post 'add_payment', to: 'payments#add_payment', as: :procesar
    resources :payments, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end

  resources :questions, only: :index


  # routes to change
  get 'make_payment', to: 'payments#make_payment', as: :make_payment
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer mt-auto py-3">
  <div class="footer-links">
    <a href="https://www.facebook.com/We-drive-it-101064268018119/?modal=admin_todo_tour"><i class="fab fa-facebook"></i></a>
    <a href="https://twitter.com/login?lang=es"><i class="fab fa-twitter"></i></a>
    <a href="https://accounts.google.com/servicelogin/signinchooser?flowName=GlifWebSignIn&flowEntry=ServiceLogin"><i class="fas fa-envelope"></i></a>
  </div>
  <div class="footer-copyright">
    <p class="text-white">Copyright 2019 - We Drive It</p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
  <%=  image_tag asset_path("new_logo.png"), class: "logo-nav-bar"  %>
  <% end %>
  <div class="dropdown" >
    <% if user_signed_in? %>
    <div class="d-flex justify-content-around">
      <% if current_user.photo? %>
      <%= cl_image_tag current_user.photo, class: "avatar"  %>

      <!-- <img src="current_user.avatar_image" class="avatar border border-dark dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown"> -->
      <% else %>
        <i class="fas fa-user-circle fa-2x text-primary" id="dropdownMenuButton" data-toggle="dropdown"></i>
      <% end %>
        <i class="fas fa-bars ml-3 mt-2 mr-3" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: #fff; font-size:28px;"></i>
      <% if current_user[:role] == "passenger" %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Perfil", profile_path, class: "dropdown-item" %>
          <%= link_to "Nueva reserva", root_path, class: "dropdown-item" %>
          <%= link_to "Editar perfil", edit_user_registration_path, class: "dropdown-item" %>
          <% if current_user.rides.present? %>
            <%= link_to "Viaje en curso", ride_status_path(current_user.rides.last), class: "dropdown-item" %>
          <% end %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      <% else %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Perfil", profile_path, class: "dropdown-item" %>
          <%= link_to "Mis viajes", dashboard_path, class: "dropdown-item" %>
          <%= link_to "Editar perfil", edit_user_registration_path, class: "dropdown-item" %>
          <%= link_to "Viaje en curso", "#", class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      <% end %>
      <% else %>
      <%= link_to "Login", new_user_session_path, class: "text-white right" %>
      <% end %>
    </div>
  </div>
</div>