config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard', as: :dashboard
  get 'profile', to: 'pages#profile', as: :profile
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cars
  resources :driver_requirement, except: [:destroy]
  get "rides/:id/status", to: "rides#status", as: :ride_status
  resources :rides, except: :destroy do
    get 'payments/add_card', to: 'payments#add_card', as: :add_card
    post 'add_payment', to: 'payments#add_payment', as: :procesar
    resources :payments, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end

  resources :questions, only: :index


  # routes to change
  get 'make_payment', to: 'payments#make_payment', as: :make_payment
end

app/views/pages/dashboard.html.erb
<div class="container-fluid">
  <h1 class="my-3">Hola <%= current_user.full_name.split(" ").map { |s| s.capitalize }.join(' ') %></h1>
  <div class="row">
    <div class="col-md-6 col-sm-12">
      <div class="my-rides">
        <h4><strong>Viajes pendientes</strong></h4>
        <div class="cards cards-ride-wrapper mb-1">
          <% if !@myrides.empty? %>
            <% @myrides.not_finished.each do |ride| %>
              <div class="card text-white bg-primary mr-3">
                <div class="card-body">
                  <h5><strong class="ejemplo">Tienes un viaje pendiente</strong></h5>
                  <p class="card-text"><strong>Pasajero:   </strong><%= ride.user.full_name.split(" ").map { |s| s.capitalize }.join(' ') %></p>
                  <p class="card-text"><strong>Desde:   </strong> <%= ride.steps.first.address %></p>
                  <p class="card-text"><strong>Hasta:   </strong> <%= ride.steps.last.address %></p>
                  <strong><p class="card-text"><i class="far fa-clock"></i> <%= ride.start_time.strftime("%b %e, %l:%M %p") %></p></strong>
                </div>
                <%= link_to "Estado del viaje", ride_path(ride), class:"btn btn-primary" %>
              </div>
            <% end %>
          <% else %>
          <p class="lead">No tienes viajes asignados!</p>
          <% end %>
        </div>
      </div>
      <div class="my-earnings w-100"></div>
    </div>
    <div class="col-md-6 col-sm-12">
      <h4><strong>Viajes Disponibles</strong></h4>
      <div class="cards mb-1 cards-ride-wrapper">
        <% @rides.not_finished.each do |ride| %>
          <div class="card shadow-sm bg-white rounded mr-3" >
            <div class="card-body">
              <div class="d-flex-space-between">
                <div class="d-flex justify-content-between">
                  <h5 class="card-title" style="font-size: 13px"><strong>Pasajero: </strong><%= ride.user.full_name.split(" ").map { |s| s.capitalize }.join(' ') %></h5>
                  <i class="fas fa-trash text-dark"></i>
                </div>
                <h6 style="color: #7CB74E; font-size:16px"><strong>Costo estimado: $<%=ride.estimated_price%></strong></h6>
              </div>
              <h6 class="mt-2"><strong>Tipo de viaje</strong></h6>
              <% if ride.service_type.name == ServiceType::OPTIONS[1] %>
                <span class="card-text">Por tramo</span>
              <% else %>
                <span class="card-text">Por hora</span>
              <% end %>
              <strong><p class="card-text my-2"><i class="far fa-clock"></i> <%= ride.start_time.strftime("%b %e, %l:%M %p") %></p></strong>
              <h6><strong>Punto de partida</strong></h6>
              <span class="card-text"><%= ride.steps.first.address %></span>
              <% if ride.service_type.name == ServiceType::OPTIONS[1] %>
              <h6><strong>Destino</strong></h6>
              <span class="card-text"><%= ride.steps.last.address %></span>
              <% else %>
              <h6><strong>Punto de devolucion</strong></h6>
              <span class="card-text"><%= ride.steps.last.address %></span>
              <% end %>
              <div class="modal fade" id="ride<%= ride.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h6 class="modal-title" id="exampleModalLongTitle"><strong>Pasajero: </strong> <%= ride.user.full_name %></h6>
                    </div>
                    <div class="modal-body">
                      <div class="shadow-sm p-3 mb-1 bg-white rounded">
                      <h6 class="modal-title" id="exampleModalLongTitle"><strong>Partida:</strong><%= ride.steps.first.address%></h6>
                      <h6 class="modal-title" id="exampleModalLongTitle"><strong>Destino:</strong><%= ride.steps.last.address%></h6>
                      <h6 class="modal-title" id="exampleModalLongTitle"><strong>Comienzo:</strong><%= ride.start_time.strftime("%b %e, %l:%M %p") %></h6>
                      <h5><strong>Costo estimado: $<%= ride.estimated_price %></strong></h5>
                      </div>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                      <%= link_to "Tomar viaje", ride_path(ride), method: :patch, remote: :true, class:"btn btn-primary" %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="card-footer p-0">
              <button type="button" class="btn btn-primary btn-block" data-toggle="modal" data-target="#ride<%= ride.id %>">
                Seleccionar viaje
              </button>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
  <!-- #4ca5eb -->
  <!-- <div class="banner-home" style="background-color: #7cc0f4 ; height: 90%" > -->
    <div class="banner-home" style="height: 30%; background-image: linear-gradient(120deg, rgba(0,0,0,0.1) 50%, rgba(0,0,0,0.1) 70%), url(<%= asset_path('bg-celeste.jpg') %>);">
    <div class="container py-5 my-4">
      <div class="text-center">
        <h1 class="pb-3"><strong>We Drive It</strong></h1>
      </div>

      <div class="text-center mb-3" id="nueva-reserva">
        <h2 class="pb-3"><strong>No esperes, nosotros te esperamos.</strong></h1>

        </div>

        <div class="pt-5 text-center">
          <h3 class="pb-2 ">Seleccioná uno de nuestros servicios</h2>

            <div class="row d-flex justify-content-between ">
              <div class="col-sm-12 col-lg-5 mt-3">
               <div class="cards-new-trip">
                <%= link_to new_ride_path(:service_type => ServiceType::OPTIONS[0]) do %>
                <div class="card-product rounded shadow-lg">
                  <%= image_tag("clock.png") %>
                  <div class="card-product-infos">
                    <h4>Chofer por hora </h4>
                  </div>
                  <i class="fas fa-arrow-right"></i>
                </div>
                <% end %>
              </div>
            </div>

            <div class="col-sm-12 col-lg-5 mt-3">
              <div class="cards-new-trip">
                <%= link_to new_ride_path(:service_type => ServiceType::OPTIONS[1]) do %>
                <div class="card-product rounded shadow-lg">
                  <%= image_tag("destination.png") %>
                  <div class="card-product-infos">
                    <h4>Chofer por tramo </h4>
                  </div>
                  <i class="fas fa-arrow-right"></i>
                </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>


    <div class="banner-home-2" style="height: 90%; background-image: linear-gradient(90deg, rgba(0,0,0,0.3) 50%, rgba(0,0,0,0.1) 70%), url(<%= asset_path('drive-with-us.jpg') %>);">
      <div class="container">
        <!-- <h1 class="py-3"><strong>No esperes, nosotros te esperamos.</strong></h1> -->
        <h1 class="py-3"><strong></strong></h1>

        <% if user_signed_in? %>
          <% if current_user.driver_requirement %>
            <p class="py-3">Conviértete en chofer y empieza a ganar dinero.</p>
          <% else %>
            <p class="py-3">Gracias a We Drive It podes disfrutar de tu tiempo como nunca antes y no preocuparte por el tráfico.</p>
          <% end %>
        <% else %>
          <p class="py-3">Conviértete en chofer y empieza a ganar dinero.</p>
        <% end %>

        <% if user_signed_in? %>
          <% if current_user.role == "driver" %>
            <% if current_user.driver_requirement %>
              <%= link_to "Ir a viajes disponibles", dashboard_path, class:"btn btn-primary" %>
            <% else %>
              <%= link_to "Conduce con nosotros", questions_path, class:"btn btn-primary" %>
            <% end %>
          <% else %>
            <%= link_to "Conduce con nosotros", questions_path, class:"btn btn-primary" %>
          <% end %>
        <% else %>
          <%= link_to "Conduce con nostoros", questions_path, class:"btn btn-primary" %>
        <% end %>
      </div>
    </div>


<!--
<header>
  <div class="overlay mx-auto w-100"></div>
  <video playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop">
    <source src="https://res.cloudinary.com/dmci1gdah/video/upload/v1573497265/chofer_hvyk89.mp4" type="video/mp4">
  </video>
  <div class="container h-100">
    <div class="d-flex h-100 text-center align-items-center">
      <div class="w-100 text-white">
        <h1 class="display-3"></h1>
        <p class="lead mb-0"><strong>Organiza tu tiempo</strong>, usa nuestro servicio y despreocupate por manejar en tu día a día</p>
      </div>
    </div>
  </div>
</header>
-->
<div class="container-fluid justify-content-between badge-light py-2" id="info-banner">
  <!-- <h1 class="text-center my-5"><strong>We drive It</strong></h1> -->
  <h1 class="text-center my-5"><strong></strong></h1>
  <div class="row">
    <div class="col-sm-12 col-lg-6 text-center ">
      <div class="p-1 mx-5 shadow">
        <div class="pt-3">
          <img src="https://image.flaticon.com/icons/svg/181/181548.svg" alt="Generic placeholder image" width="140" height="140">
        </div>
        <h3 class="my-2">Red de choferes</h3>
        <p class="mb-3 mx-5">Contamos con la red de choferes independientes más grandes de Buenos Aires, para que nunca te quedes sin chofer.</p>
      </div>
    </div>
    <div class="col-sm-12 col-lg-6 text-center">
      <div class="p-1 my-5 mx-5 shadow">
        <div class="pt-3">
          <img src="https://image.flaticon.com/icons/svg/74/74373.svg" alt="Generic placeholder image" width="140" height="140">
        </div>
        <h3 class="my-2">Tu seguridad es importante</h3>
        <p class="mb-3 mx-3">Para que te muevas sin preocupaciones, todos nuestros viajes están geolocalizados y tanto los pasajeros como los conductores están identificados.</p>
      </div>
    </div>
    <div class="col-sm-12 col-lg-6 text-center">
      <div class="p-1 mx-5 shadow">
        <div class="pt-3">
          <img src="https://image.flaticon.com/icons/svg/149/149322.svg" alt="Generic placeholder image" width="140" height="140">
        </div>
        <h3 class="my-2">Contratá por horas</h3>
        <p class="mb-3 mx-3">Podés contratar un chofer por la cantidad de hora que necesitás y que te lleve a multiples destinos.</p>
      </div>
    </div>
    <div class="col-sm-12 col-lg-6 text-center">
      <div class="p-1 my-5 mx-5 shadow">
        <div class="pt-3">
          <img src="https://image.flaticon.com/icons/svg/1179/1179054.svg" alt="Generic placeholder image" width="140" height="140">
        </div>
        <h3 class="my-2">Contratá por tramo</h3>
        <p class="mb-3 mx-3">Si solo querés que te lleve a un solo destino, como ser al aeropuerto, una reunion de negocios, tu trabajo o a algun viaje, contratá por trayecto recorrido.</p>
      </div>
    </div>
  </div>
</div>

<!--
<div class="container-fluid justify-content-space-between badge-light py-2" id="Nosotros">
  <h1 class="text-center my-5"><strong>Nuestro equipo</strong></h1>
  <div class="row">
    <div class="col-sm-12 col-lg-3 text-center">
      <img class="rounded-circle" src="https://avatars2.githubusercontent.com/u/54599926?s=460&v=4" alt="Generic placeholder image" width="80" height="80">
      <h3 class="my-2">Gaspar Baldunciel</h3>
      <h3>CEO</h3>
      <a href="https://www.linkedin.com/in/gaspar-baldunciel-30b60a119" target='_blank'><i class="fab fa-2x fa-linkedin"></i></a>
      <p class="mb-5">Dueño de Clifftone. Se unió a LeWagon en Agosto del 2019. Co-fundador de We Drive It.</p>
    </div>
    <div class="col-sm-12 col-lg-3 text-center">
      <img class="rounded-circle" src="https://avatars0.githubusercontent.com/u/54510877?s=460&v=4" alt="Generic placeholder image" width="80" height="80">
      <h3 class="my-2">Gastón Lascano</h3>
      <h3>CFO</h3>
      <a href="https://www.linkedin.com/in/gaston-lascano-77a932163" target='_blank'><i class="fab fa-2x fa-linkedin"></i></a>
      <p class="mb-5">Especialista en management de negocios y fanático del Wakeboard. Se unió a LeWagon en Agosto del 2019. Co-fundador de We Drive It.</p>
    </div>
    <div class="col-sm-12 col-lg-3 text-center">
      <img class="rounded-circle" src="https://avatars1.githubusercontent.com/u/54502513?s=460&v=4" alt="Generic placeholder image" width="80" height="80">
      <h3 class="my-2">Enzo Crivelli</h3>
      <h3>CMO</h3>
      <a href="https://www.linkedin.com/in/enzo-crivelli-5b3b6012a" target='_blank'><i class="fab fa-2x fa-linkedin"></i></a>
      <p class="mb-5">Especialista en Marketing y triatleta. Se unió a LeWagon en Agosto del 2019. Co-fundador de We Drive It.</p>
    </div>
    <div class="col-sm-12 col-lg-3 text-center">
      <img class="rounded-circle" src="https://avatars1.githubusercontent.com/u/54517348?s=460&v=4" alt="Generic placeholder image" width="80" height="80">
      <h3 class="my-2">Agustín Greissing </h3>
      <h3>COO</h3>
      <a href="https://www.linkedin.com/in/agustingreissing" target='_blank'><i class="fab fa-2x fa-linkedin"></i></a>
      <p class="mb-5">Economista. Apasionado de la lectura y de la cocina. Se unió a LeWagon en Agosto del 2019. Co-fundador de We Drive It.</p>
    </div>
  -->  </div>
</div>

app/views/pages/profile.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1515895309288-a3815ab7cf81?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60); background-repeat: no-repeat; background-size: cover;">
  <div class="container col-md-6 col-sm-12 d-flex text-align-center justify-content-center">
    <div class="container profile-card mt-3 mb-3">
      <div class="text-center mt-5">
        <% if current_user.photo? %>
         <%= cl_image_tag current_user.photo, class: "avatar-profile" %>
        <% else %>
         <i class="fas fa-user-circle fa-2x text-primary" id="profile-empty-avatar"></i>
        <% end %>
      </div>
      <% if current_user[:role] == "passenger" %>
        <% if current_user.rides.present? %>
          <div class="profile-steps text-center mt-5 border-bottom">
            <h6><%= link_to "Viaje en curso", ride_status_path(current_user.rides.last), class: "link-style"  %></h6>
          </div>
        <% end %>
        <div class="profile-steps text-center mt-5 border-bottom">
          <h6><%= link_to "Nueva reserva - tramo", new_ride_path(service_type: "One way trip"), class: "link-style"  %></h6>
        </div>
        <div class="profile-steps text-center mt-5 border-bottom">
          <h6><%= link_to "Nueva reserva - hora", new_ride_path(service_type: "One way trip"), class: "link-style"  %></h6>
        </div>
        <div class="profile-steps text-center mt-5 border-bottom">
          <h6><%= link_to "Editar perfil", edit_user_registration_path, class: "link-style"  %></h6>
        </div>
        <div class="profile-steps text-center mt-5 mb-5 border-bottom">
          <h6>Mis autos</h6>
        </div>
      <% else %>
        <div class="profile-steps text-center mt-5 border-bottom">
          <h6><%= link_to "Mis viajes", dashboard_path, class: "link-style"  %></h6>
        </div>
        <div class="profile-steps text-center mt-5 border-bottom">
          <h6><%= link_to "Tomar viaje", dashboard_path, class: "link-style"  %></h6>
        </div>
        <div class="profile-steps text-center mt-5 border-bottom">
          <h6><%= link_to "Editar perfil", edit_user_registration_path, class: "link-style"  %></h6>
        </div>
        <div class="profile-steps text-center mt-5 mb-5 border-bottom">
          <h6>Mis autos</h6>
        </div>
      <% end %>
      <div class="sign-out-btn border border-primary mb-5 text-center p-2">
        <h6><%= link_to "Cerrar sesion", destroy_user_session_path  %></h6>
      </div>
    </div>
  </div>
</div>