config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard', as: :dashboard
  get 'profile', to: 'pages#profile', as: :profile
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cars
  resources :driver_requirement, except: [:destroy]
  get "rides/:id/status", to: "rides#status", as: :ride_status
  resources :rides, except: :destroy do
    get 'payments/add_card', to: 'payments#add_card', as: :add_card
    post 'add_payment', to: 'payments#add_payment', as: :procesar
    resources :payments, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end

  resources :questions, only: :index


  # routes to change
  get 'make_payment', to: 'payments#make_payment', as: :make_payment
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :ride
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  protect_from_forgery except: [:add_payment, :create]

  def failed
    authorize :payment, :failed?
  end

  def new
    @ride = Ride.find(params[:ride_id])
    authorize @ride
    @payment = Payment.new
    @payment.ride = @ride
    @review = Review.new
    # current_user.rides.where(status: 'pending').find(params[:ride_id])
  end

  def create
    @payment = Payment.new
    @payment.ride = @ride
    @ride = Ride.find(params[:ride_id])
    @payment.ride = @ride
    authorize @payment

    # create MP payment and save status
    require 'mercadopago'
    $mp = MercadoPago.new(ENV["MP_PRIVATE_TOKEN"])

    token = params[:token]
    payment_method_id = params[:payment_method_id]
    installments = 1
    issuer_id = params[:issuer_id]

    mp_payment = {}
    mp_payment[:transaction_amount] = @ride.estimated_price
    mp_payment[:token] = token
    mp_payment[:description] = 'Adding a new user to wedriveit'
    mp_payment[:installments] = installments
    mp_payment[:issuer_id] = issuer_id
    mp_payment[:payer] = {
      id: current_user.mp_customer_id
    }

    payment_response = $mp.post("/v1/payments", mp_payment)

    if payment_response["status"] == "201" && payment_response["response"]["status"] == "approved"
      @payment.ride = @ride
      if @payment.save!
        redirect_to new_ride_review_path(@ride)
      else
        render :new
      end
    end
  end

  def add_payment
    @payment = Payment.new
    authorize @payment
    # make a payment
    # if payment its ok, then
      # create a customer
      # save customer_id to user
      # add a card to the customer
      # save card_id to user

      token = params[:token]
      payment_method_id = params[:payment_method_id]
      installments = 1
      issuer_id = params[:issuer_id]

      require 'mercadopago'

      $mp = MercadoPago.new(ENV["MP_PRIVATE_TOKEN"])

      payment = {}
      payment[:transaction_amount] = 1
      payment[:token] = token
      payment[:description] = 'Adding a new user to wedriveit'
      payment[:installments] = installments
      payment[:issuer_id] = issuer_id
      payment[:payer] = {
        email: current_user.email
      }

      payment_response = $mp.post("/v1/payments", payment)
      response = {}
      response[:payment_response] = payment_response

      if payment_response["status"] == "201"
      # check if customer exists
        search_customer_id = $mp.get("https://api.mercadopago.com/v1/customers/search?email=#{current_user.email}")
      if search_customer_id["response"]["results"].present?
        current_user.mp_card_id = search_customer_id["response"]["results"][0]["cards"][0]["id"]
        current_user.mp_customer_id = search_customer_id["response"]["results"][0]["id"]
        current_user.save
      else
        # create a customer
              # create a customer
        customer_response = $mp.post("/v1/customers", {email: current_user.email})
        # save customer_id to user
        current_user.mp_customer_id = customer_response["response"]["id"]
        # add a card to the customer
        card_response = $mp.post("/v1/customers/#{customer_response["response"]["id"]}/cards", {token: token})
        current_user.mp_card_id = card_response["response"]["id"]
        current_user.save
      end

      # # save customer_id to user

      # # add a card to the customer
      # card_response = $mp.post("/v1/customers/#{current_user.mp_customer_id}/cards", {token: token})

      # current_user.mp_card_id = card_response["response"]["id"]
      # current_user.save
      # # save card_id to user
      # response[:customer_response] = customer_response
      # response[:card_response] = card_response
    end
    redirect_to profile_path
  end
  def add_card
    skip_authorization
    if current_user.mp_card_id?
      return redirect_to ride_status_path(params[:ride_id])
    end
    @ride = Ride.find(params[:ride_id])
    @payment = Payment.new(ride: @ride)
    authorize @payment
  end

  private

  def payment_params
    params.require(:payment).permit(:params?)
  end
end

app/views/payments/add_card.html.erb
<div class="banner-add-card d-flex justify-content-center align-items-center">
  <div class="container col-md-6 col-sm-12 d-flex text-align-center justify-content-center">
    <div class="rounded form-show-ride" style="height: 100%; width: 90%; background-color: white;">
      <div class="notification d-flex justify-content-center border border-secondary m-3">
        <div class="notification-content p-4 border-rounded">
          <h2 class="mb-3">Hola <strong><%= current_user.full_name.split(" ").map { |s| s.capitalize }.join(' ') %></strong> gracias por elegirnos!</h2>
          <h3 class="mb-3">A continuación necesitaremos que vincules tu tarjeta de credito a tu cuenta de We Drive It</h3>
          <h3 class="mb-3">Se realizará un <strong>cargo inicial de $2</strong> para asegurarnos que la vinculación haya sido exitosa</h3>
          <h3 class="mb-3">No te preocupes, el cargo se te descontara de tu factura final.</h3>
        </div>
      </div>
      <div>
        <form action="<%= ride_procesar_path(@ride) %>" method="POST">
          <script
          data-elements-color="#4ca5ea"
          data-header-color="#4ca5ea"
          src="https://www.mercadopago.com.ar/integrations/v1/web-tokenize-checkout.js"
          data-public-key="<%= ENV['MP_PUBLIC_TOKEN']%>"
          data-transaction-amount="2.00"
          data-button-label="Agregar tarjeta">
          </script>
        </form>
     </div>
   </div>
  </div>
</div>

app/views/payments/make_payment.html.erb
<form action="/procesar-pago" method="POST">
  <script
    src="https://www.mercadopago.com.ar/integrations/v1/web-tokenize-checkout.js"
    data-public-key="<%= ENV['MP_PUBLIC_KEY']%>"
    data-transaction-amount="100.00"
    data-customer-id="<%= current_user.mp_customer_id %>"
    data-card-ids="<%= current_user.mp_card_id %>">
  </script>
</form>

app/views/payments/new.html.erb
<div class="banner " style="background-color: white;">

  <div class="container" style="min-height: 90vh;">
    <div class="row justify-content-center">
      <div class="col-12 col-md-6 my-5">
        <div class="card text-center" style="background: rgba(220,220,220,0.8); box-shadow: 2px, 2px 2px rgba( 0, 0, 0, 0.8);">
          <div class="card-header">
            <strong> TU VIAJE HA FINALIZADO</strong>
          </div>
          <div class="card-body">
            <h5 class="card-title">Resumen:</h5>
            <p class="card-text" style="color:black">Inicio: <%=@ride.start_time.strftime('%b %e, %l:%M %p') %></p>
            <p class="card-text" style="color:black" >Final: <%=@ride.end_time.strftime('%b %e, %l:%M %p') %></p>
            <p class="card-text" style="color:black">Total horas: <%=@ride.total_time_ride %></p>
            <p class="card-text text-body"> <strong>Total a pagar: $<%= @ride.estimated_price %> </strong></p>
          </div>
          <div class="card-footer text-muted">
            <form action="<%= ride_payments_path(@ride) %>" method="POST">
            <script
              src="https://www.mercadopago.com.ar/integrations/v1/web-tokenize-checkout.js"
              data-elements-color="#0B5FC4"
              data-header-color="#0B5FC4"
              data-public-key="<%= ENV['MP_PUBLIC_TOKEN'] %>"
              data-transaction-amount="<%= @ride.estimated_price %>"
              data-button-label="Confirmar y pagar"
              <% if current_user.mp_customer_id? %>
                data-customer-id="<%= current_user.mp_customer_id %>"
                data-card-ids="<%= current_user.mp_card_id %>">
              <% end %>
              >
            </script>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
</div>