config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard', as: :dashboard
  get 'profile', to: 'pages#profile', as: :profile
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cars
  resources :driver_requirement, except: [:destroy]
  get "rides/:id/status", to: "rides#status", as: :ride_status
  resources :rides, except: :destroy do
    get 'payments/add_card', to: 'payments#add_card', as: :add_card
    post 'add_payment', to: 'payments#add_payment', as: :procesar
    resources :payments, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end

  resources :questions, only: :index


  # routes to change
  get 'make_payment', to: 'payments#make_payment', as: :make_payment
end

app/models/ride.rb
class Ride < ApplicationRecord

  STEPS = {
    "One way trip" => ["Punto de partida", "Destino"],
    "Multiple ways trip" => ["Punto de partida", "Destino principal", "Punto de regreso"]
  }

  MESSAGES = ["Tu chofer va en camino", "Tu chofer ha llegado", "En camino a tu destino", "Tu viaje ha finalizado"]

  enum status: ["CANCELADO", "PENDIENTE", "ASIGNADO", "EN CAMINO", "HE LLEGADO", "COMENZAR VIAJE", "VIAJE TERMINADO"]
  has_many :reviews, dependent: :destroy
  has_many :steps, dependent: :destroy
  has_one :car,  through: :user
  has_one :payment
  accepts_nested_attributes_for :steps
  belongs_to :user, optional: true
  belongs_to :service_type
  belongs_to :driver, class_name: 'User', foreign_key: "driver_id", optional: true
  # validates :status, presence: true
  # , inclusion: { in: status.keys }
  validates :start_time, presence: true
  validates :end_time, presence: true

  scope :not_finished, -> { where.not(status: 'VIAJE TERMINADO') }

  def set_status
    unless status == "VIAJE TERMINADO"
      if !actual_start_time.nil? && actual_end_time.nil?
        self.status = "COMENZAR VIAJE"
      elsif !actual_start_time.nil? && !actual_end_time.nil?
        self.status = "VIAJE TERMINADO"
      else
        self.status = ["PENDIENTE", "CANCELADO"].sample
      end
    end
  end

  def pretty_time
    estimatd_new_time = estimated_time_ride.to_i.divmod(60)
    "#{estimatd_new_time[0]} hrs #{estimatd_new_time[1]} mins"
  end

  def completed?
    status == "VIAJE TERMINADO"
  end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create]
  before_action :set_ride, only: [:show, :edit, :update, :status]

  def index
    @rides = policy_scope(Ride).order(created_at: :desc)
  end

  def show
  end

  def new
    @ride = Ride.new
    steps = 2
    if params[:service_type].present?
      @ride.service_type = ServiceType.find_by_name(params[:service_type])
      steps = @ride.service_type.name == ServiceType::OPTIONS[1] ? 2 : 3
    end
    steps.times do |order|
      @ride.steps.build(order: order + 1)
    end
    authorize @ride
  end

  def create
    @ride = Ride.new(ride_params)
    @ride.save
    session[:ride_id] = @ride.id
    @ride.user = current_user if current_user.present?
    authorize @ride
    if @ride.save
      RideMailer.create_confirmation(@ride).deliver_now unless @ride.user.nil?
      redirect_to ride_path(@ride)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @ride.status == "PENDIENTE"
      @ride.driver_id = current_user.id
      @ride.status = "ASIGNADO"
      @ride.save
      respond_to do |format|
        format.html { redirect_to ride_path(@ride) }
        format.js # <-- will render `app/views/rides/update.js.erb  `
      end
    else
      @ride.status = params[:ride][:status]
      @ride.save
      return redirect_to @ride
    end
  end

  def status
    @ride = Ride.find(params[:id])
    redirect_to new_ride_payment_path(@ride) if @ride.completed?
  end

  private

  def ride_params
    params.require(:ride).permit(:start_time, :end_time, :content, :service_type_id, :status, :estimated_time_ride, :estimated_price, steps_attributes: [:address, :order])
  end

  def set_ride
    @ride = Ride.find(params[:id])
    authorize @ride
  end
end

app/views/rides/_show_driver.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-5 mt-4">
      <div class="text-center shadow-sm p-3 mb-4 rounded" style="background: rgba(200,200,200,0.5)">
        <h4 class="font-weight-light mt-1"><strong>VIAJE EN CURSO</strong></h4>
      </div>
      <div class="my-2 shadow-sm p-3 mb-3 rounded" style="background: rgba(200,200,200,0.4)">
        <div class="container text-center my-2">
          <div style="">
            <% if @ride.user.cars.first.photo != nil %>
            <%= cl_image_tag( @ride.user.cars.first.photo , height: '230', width: '270', class:"mx-auto;", style:"object-fit: cover;") %>
            <% else %>
            <%= cl_image_tag( @ride.user.photo , height: '230', width: '270', class:"mx-auto;", style:"object-fit: cover;") %>
            <% end %>
          </div>
          <div class="mt-4">
            <h2><%=@ride.user.full_name.split(" ").map { |s| s.capitalize }.join(' ') %></h2>
            <h3><%=@ride.user.cars.first.brand%> - <%= @ride.user.cars.first.model%></h3>
            <h6><strong>Observaciones: </strong><%=@ride.content%></h6>
          </div>
        </div>
      </div>

      <div class="text-center shadow-sm p-3 mb-5 rounded" style="background: rgba(200,200,200,0.4)">
        <% if @ride.status == "VIAJE TERMINADO"%>
        <h5>Viaje finalizado!</h5>
        <% else %>
        <% next_status = @ride.status_before_type_cast + 1 %>
        <%= link_to "#{Ride::statuses.index(next_status)}", ride_path(@ride, ride: { status: Ride::statuses.index(next_status)}) , method: :patch, class: "btn btn-primary btn-block" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rides/_show_passenger.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1515895309288-a3815ab7cf81?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60); background-repeat: no-repeat; background-size: cover;">
  <div class="container col-md-6 col-sm-12 d-flex text-align-center justify-content-center">
    <div class="rounded form-show-ride" style="height: 100%; width: 90%; background-color: white;">

      <%= simple_form_for @ride do |m| %>

      <div class="form-first pt-3"  style="background-color:black">
        <h3 align="center" style="color:white"><strong>Confirmar datos de tu viaje</strong></h3>
        <div class="background-color-black container mt-3 pb-3">
          <%= m.hidden_field :service_type_id, value: @ride.service_type.id %>
          <%= m.simple_fields_for :steps do |f| %>
          <div class="active-dark-4 my-2">
            <%= f.input :address, placeholder: "#{Ride::STEPS[@ride.service_type.name][f.object.order - 1]}", label: false, class: "form-control", input_html: { class: "ride_address", data: {algoliaAppId: ENV["APPLICATION_ID"], algoliaAppKey: ENV['ALGOLIA_API_KEY']} } %>
            <%= f.hidden_field :order, value:f.object.order %>
          </div>
          <% end %>
        </div>
      </div>
      <div class="container">
          <p class="mt-3 mb-0 text-dark"><strong>Partida</strong></p>
          <div class="d-flex">
            <div class="date-choose datetime-start pb-0">
              <p class="text-dark">Día</p>
              <p class="text-dark"><%= ride.start_time.strftime('%Y-%m-%d') %></p>
            </div>
            <div class="date-choose datetime-end pb-0 text-dark">
              <p class="text-dark">Hora de salida</p>
              <p class="text-dark"><%= ride.start_time.strftime('%I:%M:%S %p') %></p>
              <div class="d-flex">
              </div>
            </div>
          </div>
        </div>
      <div class="punteado border-dotted border-secondary border-right-0 border-left-0 border-top-0 border-bottom-0 my-3 rounded p-1 mx-3 text-center">
        <div class="text-left mb-3 mt-1">
          <h7><strong>- Partida:</strong> <%= @ride.steps.first.address %>.</h7>
        </div>
        <div class="text-left mb-3">
          <h7><strong>- Destino:</strong> <%= @ride.steps.last.address %>.</h7>
        </div>
        <div class="text-left mb-1">
          <h7><strong>- Tiempo de viaje estimado</strong> - <%= @ride.pretty_time %>.</h7>
        </div>
      </div>
      <div class="punteado border-doted border-primary border-right-0 border-left-0 my-5 rounded p-1 mx-3 text-center">
        <div class="my-3">
          <h5>TOTAL ESTIMADO <strong>$<%= @ride.estimated_price %></strong></h5>
        </div>
      </div>
      <div class="mx-3">
        <h3 class="creating-line my-5"><span>Chofer</span></h3>
      </div>

      <div class="notification d-flex justify-content-center border border-secondary m-3">
        <% if @ride.driver.present? %>
        <div class="notification-img row flex-column p-4">
          <img src='<%= @ride.driver.photo %>' class="avatar-large" >
          <div class="stars-chofer">
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="far fa-star"></i>
          </div>
        </div>
        <div class="notification-content p-4">
          <h4 class="mb-3"><strong>Nombre: </strong><%= @ride.driver.full_name %></h4>
          <h4 class="mb-3"><strong>Edad: </strong>26 años</h4>
          <h4 class="mb-3"><strong>Calificacion promedio: </strong>4.5</h4>
          <h4 class="mb-3"><strong>Observaciones: </strong>Gran conductor con habilidades para diferentes modos de manejo.</h4>
        </div>
        <% else %>
        <div class="notification-img row flex-column p-4">
          <div class="card">
<!--             <img src="https://media0.giphy.com/media/md8IyVfwAr8xW/giphy.webp?cid=790b7611fdf8cd70386714dcb1395bf0676f32229934caa6&rid=giphy.webp" alt="" class="w-100">
 -->          </div>
          <div class="notification-content p-4">
            <h4 class="mb-3"><strong>Chofer: </strong>Estamos buscando el mejor chofer para tu viaje y tu experiencia unica.</h4>
            <h4 class="mb-3"><strong>Confirme su viaje mientras buscamos un chofer que se adapte a su demanda</strong></h4>
          </div>
        </div>
        <% end %>
      </div>
      <% end %>
      <div class="border border-secondary my-5  bg-primary rounded p-1 mx-3 text-center">
        <% if @ride.user.payment_method? %>
          <%= link_to "Confirmar", ride_status_path(@ride), class: "btn btn-primary" %>
        <% else %>
          <%= link_to "Confirmar", ride_add_card_path(@ride), class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rides/driver_show.html.erb
<div class="container">
  <div class="row justify-content-center">

    <div class="col-12 col-md-5 mt-4">
      <div class="text-center shadow-sm p-3 mb-4 rounded" style="background: rgba(200,200,200,0.5)">
        <h4 class="font-weight-light mt-1"><strong>VIAJE EN CURSO</strong></h4>
      </div>
      <div class="my-2 shadow-sm p-3 mb-3 rounded" style="background: rgba(200,200,200,0.4)">
        <div class="container text-center my-2">
          <div class="">
            <%= image_tag("feli.jpg", height: '140', width: '140', class:"mx-auto rounded-circle") %>
          </div>
          <div class="mt-4">
            <h2>Felipe Hernandez</h2>
            <h6>Chofer profesional</h6>
            <h6>Buenos Aires, Argentina.</h6>
          </div>
        </div>
      </div>

      <div class="text-center shadow-sm p-3 mb-5 rounded" style="background: rgba(200,200,200,0.4)">
        <% if @ride.status == "VIAJE TERMINADO"%>
        <h5>Viaje finalizado!</h5>
        <% else %>
        <% next_status = @ride.status_before_type_cast + 1 %>
        <%= link_to "#{Ride::statuses.index(next_status)}", ride_path(@ride, ride: { status: Ride::statuses.index(next_status)}) , method: :patch, class: "btn btn-primary btn-block" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rides/edit.html.erb
<h1>EDIT</h1>

app/views/rides/new.html.erb
<script>
  let serviceType = "<%= @ride.service_type.name %>";
</script>

<%= simple_form_for @ride do |m| %>

<div class="container-fluid px-0">
  <div class="row no-gutters position-relative">
    <div class="col-md-8 order-md-last">
     <div
     id="map"
     style="width: 100%;
     height: 800px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
     ></div>
   </div>
   <div class="col-md-4 order-md-first" style="background-color:white" >
    <div class="form-first pt-3"  style="background-color:black">
      <h3 align="center" style="color:white"><strong>Datos de tu viaje</strong></h3>
      <div class="background-color-black container mt-3 pb-3">
        <%= m.hidden_field :service_type_id, value: @ride.service_type.id %>
        <%= m.simple_fields_for :steps do |f| %>
        <div class="active-dark-4 my-2">
          <%= f.input :address, placeholder: "#{Ride::STEPS[@ride.service_type.name][f.object.order - 1]}", label: false, class: "form-control", input_html: { class: "ride_address", data: {algoliaAppId: ENV["APPLICATION_ID"], algoliaAppKey: ENV['ALGOLIA_API_KEY']} } %>
          <%= f.hidden_field :order, value:f.object.order %>
        </div>
        <% end %>
      </div>
    </div>
    <div class="container bg-white">
      <div class="mb-3">
        <div>
          <p class="mt-3 mb-0">Partida</p>
          <div class="d-flex">
            <div class="date-choose datetime-start pb-0">
              <p>Día</p>
              <input class="datepicker" id="start-date"></input>
            </div>
            <div class="date-choose datetime-end pb-0">
              <p>Hora</p>
              <div class="d-flex">
                <select id="start-time-hour">
                  <% (0..23).to_a.each do |num| %>
                  <option value="<%= num %>" data-type="primary"><%= num %> hs</option>
                  <% end %>
                </select>
                <select id="start-time-minute">
                  <% ["00", "15", "30", "45"].each do |num| %>
                  <option value="<%= num %>" data-type="primary"><%= num %></option>
                  <% end %>
                </select>
              </div>
            </div>
          </div>
        </div>
        <% if @ride.service_type.name != ServiceType::OPTIONS[1] %>
        <div>
          <p class="mt-1 mb-0">Regreso</p>
          <div class="d-flex">
            <div class="date-choose datetime-start pb-0">
              <p>Día</p>
              <input class="datepicker" id="start-date-2"></input>
            </div>
            <div class="date-choose datetime-end pb-0">
              <p>Hora</p>
              <div class="d-flex">
                <select id="start-time-hour-2">
                  <% (0..23).to_a.each do |num| %>
                  <option value="<%= num %>" data-type="primary"><%= num %> hs</option>
                  <% end %>
                </select>
                <select id="start-time-minute-2">
                  <% ["00", "15", "30", "45"].each do |num| %>
                  <option value="<%= num %>" data-type="primary"><%= num %></option>
                  <% end %>
                </select>
              </div>
            </div>
          </div>
        </div>
        <% end %>
        <%= m.hidden_field :start_time, as: :hidden, required: false, label: false, id: "start_time", type: "hidden" %>
        <%= m.hidden_field :end_time,  as: :hidden, required: false, label: false, id: "end_time", type: "hidden" %>
      </div>

      <div class="form-group my-2" style="">
        <%= m.input :content, placeholder: 'Añade información relevante para tu chofer', label: false, class: "form-control", id:"exampleFormControlTextarea1", rows:"3" %>
      </div>
      <p class="mb-2">
        <small>Estimated trip time:</small><br>
        <strong id="render-time">-</strong>
      </p>
      <p>
        <small>Estimated price:</small><br>
        <strong id="render-price">-</strong>
      </p>
      <%= m.hidden_field :estimated_price, as: :hidden, type: "hidden" %>
      <%= m.hidden_field :estimated_time_ride, as: :hidden, type: "hidden" %>
      <%= m.input :status, :as => :hidden, :input_html => { :value => "PENDIENTE" } %>
      <%= m.button :submit, value:"Pedir Chofer", class: "btn btn-block btn-success mb-5 text-center disabled", disabled:"disabled", id:"chofer_request" %>

    </div>
  </div>
</div>
<% end %>


<script>
  window.addEventListener('load', function () {
    const locateUser = document.querySelector(".mapboxgl-ctrl-icon")
    locateUser.click();
  })
</script>

app/views/rides/show.html.erb
<% if current_user.driver? %>
  <%= render "show_driver", ride: @ride %>
<% else %>
  <%= render "show_passenger", ride: @ride %>
<% end %>

app/views/rides/status.html.erb
<div class="banner vh-100 vw-100" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1474471981552-e3084590b868?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60); background-size: cover;">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-md-6 mt-3">
        <div class="text-center shadow-sm p-3 mb-4 rounded" style="background: rgba(200,200,200,0.9)">
          <h4 class="font-weight-light mt-1"><strong>VIAJE EN CURSO</strong></h4>
        </div>
        <div class="my-2 shadow-sm p-3 mb-2 rounded" style="background: rgba(200,200,200,0.8)">
          <div class="container text-center my-2">
            <% if @ride.driver.nil? %>
            <h2>Esperando a que se asigne su chofer...</h2>
            <% else %>
            <div class="">
              <h2> - Tu chofer - </h2>
              <%= cl_image_tag(@ride.driver.photo, height: '140', width: '140', class:"mx-auto rounded-circle") %>
            </div>
            <div class="mt-4">
              <h2> <%= @ride.driver.full_name %></h2>
              <!-- <h6>Chofer profesional</h6> -->
              <!-- <h6>Buenos Aires, Argentina.</h6> -->
              <button type="button" class="btn btn-secondary">Mensaje</button>
              <button type="button" class="btn btn-secondary">Llamar</button>
            </div>
            <% end %>
          </div>

        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row justify-content-center mt-3">
      <div class="col-12">
        <div class="mx-md-5 shadow-sm py-3 px-5 px-md-3 mb-4 rounded" style="background: rgba(200,200,200,0.8)">
          <div style="" class="d-flex flex-md-column">
            <div class="position-relative flex-grow-0  d-flex flex-column justify-content-around flex-md-row">
              <div class="h-100 flex-grow-0 rounded-pill d-flex flex-column justify-content-around flex-md-row journey-path-wrapper">
                <% Ride::MESSAGES.count.times do |num| %>
                <div class="rounded-circle <%= Ride::statuses[@ride.status] <= (num + 2) ? 'bg-secondary ' : 'bg-primary' %>" style="height: 20px; width: 20px;"></div>
                <% end %>
              </div>
              <div class="rounded-pill bg-secondary journey-path position-absolute journey-path-completed">
                <div class="bg-primary rounded-pill wandh-<%= (Ride::statuses[@ride.status] - 2) * 25  %>"></div>
              </div>
            </div>
            <div class="flex-grow-0 my-2 rounded-pill d-flex flex-column justify-content-around flex-md-row mt-md-4 icon-wrapper ml-3 ml-md-0 mx-md-auto">
              <%= image_tag("car-front#{ Ride::statuses[@ride.status] < 3 ? '' : '-blue' }.png", width: 35) %>
              <%= image_tag("home#{ Ride::statuses[@ride.status] < 4 ? '' : '-blue' }.png", width: 35) %>
              <%= image_tag("location#{ Ride::statuses[@ride.status] < 5 ? '' : '-blue' }.png", width: 35) %>
              <%= image_tag("racing-flag#{ Ride::statuses[@ride.status] < 6 ? '' : '-blue' }.png", width: 35) %>
            </div>

            <div class="flex-grow-1 d-md-flex justify-content-around text-align-center">
              <% Ride::MESSAGES.each_with_index do |message, index|  %>
                <div class="d-flex align-items-center m-0 pl-3 py-3 pr-0 px-md-2 py-md-0">
                  <p class="<%= Ride::statuses[@ride.status] <= (index + 2) ? 'bg-secondary ' : 'bg-primary' %> border-rounded text-white w-md-100 m-md-0 text-center rounded font-weight-normal text-uppercase p-2 m-0"><%= message %></p>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rides/update.js.erb
/*const cardPending = document.querySelector("[data-ride='<%= @ride.id %>']")
console.log(cardPending)
document.querySelector('.my-rides .cards').prepend(cardPending);
cardPending.remove();*/
/*var element = document.querySelector("#ride<%= @ride.id %>")
element.remove();*/
$('#ride<%= @ride.id %>').modal('hide')
location.reload();